// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4IzH-nsMoq1_pVBIW7sAb0AhatJiKAVM',
    appId: '1:244614467814:web:168316db42a00f4b18ab27',
    messagingSenderId: '244614467814',
    projectId: 'g-weather-forecast-2025',
    authDomain: 'g-weather-forecast-2025.firebaseapp.com',
    storageBucket: 'g-weather-forecast-2025.firebasestorage.app',
    measurementId: 'G-GTP2GTNSPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKtMIi5uH1CGMvC9GHeLVF8nWh-5Sm4kE',
    appId: '1:244614467814:android:4144612599ab581718ab27',
    messagingSenderId: '244614467814',
    projectId: 'g-weather-forecast-2025',
    storageBucket: 'g-weather-forecast-2025.firebasestorage.app',
  );
}
